### ISSUE TITLE
Error: unrecognized -march target: armv5

### ISSUE THREAD

**Issue by autra** [lgeek/u-boot-okreader#4]
Hi !

Trying to build on ubuntu 22.04 with gcc.

Ive added `export CROSS_COMPILE=arm-linux-gnueabi- ` to my build script, but when running `make mx50_rdp_config`, I have the following logs:

```
arm-linux-gnueabi-gcc: error: unrecognized -march target: armv5
arm-linux-gnueabi-gcc: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2; did you mean ‘armv4’?
arm-linux-gnueabi-gcc: error: missing argument to ‘-march=’
arm-linux-gnueabi-gcc: error: unrecognized -march target: armv5
arm-linux-gnueabi-gcc: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2; did you mean ‘armv4’?
arm-linux-gnueabi-gcc: error: missing argument to ‘-march=’
Configuring for mx50_rdp board...
```

Any idea what's wrong? Something not right in my toolchain?

---

I tried modifying the value of -march in `cpu/arm_cortexa8/config.mk` to `PLATFORM_CPPFLAGS += -march=armv5t` . Then, `make mx50_rdp_config` succeed, but make fails with these errors:

```
board.c:131:6: error: ‘coloured_LED_init’ aliased to external symbol ‘__coloured_LED_init’
  131 | void coloured_LED_init(void)__attribute__((weak, alias("__coloured_LED_init")));
      |      ^~~~~~~~~~~~~~~~~
board.c:147:6: error: ‘blue_LED_off’ aliased to external symbol ‘__blue_LED_off’
  147 | void blue_LED_off(void) __attribute__((weak, alias("__blue_LED_off")));
      |      ^~~~~~~~~~~~
board.c:145:6: error: ‘blue_LED_on’ aliased to external symbol ‘__blue_LED_on’
  145 | void blue_LED_on(void) __attribute__((weak, alias("__blue_LED_on")));
      |      ^~~~~~~~~~~
board.c:143:6: error: ‘yellow_LED_off’ aliased to external symbol ‘__yellow_LED_off’
  143 | void yellow_LED_off(void) __attribute__((weak, alias("__yellow_LED_off")));
      |      ^~~~~~~~~~~~~~
board.c:141:6: error: ‘yellow_LED_on’ aliased to external symbol ‘__yellow_LED_on’
  141 | void yellow_LED_on(void) __attribute__((weak, alias("__yellow_LED_on")));
      |      ^~~~~~~~~~~~~
board.c:139:6: error: ‘green_LED_off’ aliased to external symbol ‘__green_LED_off’
  139 | void green_LED_off(void) __attribute__((weak, alias("__green_LED_off")));
      |      ^~~~~~~~~~~~~
board.c:137:6: error: ‘green_LED_on’ aliased to external symbol ‘__green_LED_on’
  137 | void green_LED_on(void) __attribute__((weak, alias("__green_LED_on")));
      |      ^~~~~~~~~~~~
board.c:135:6: error: ‘red_LED_off’ aliased to external symbol ‘__red_LED_off’
  135 | void red_LED_off(void)       __attribute__((weak, alias("__red_LED_off")));
      |      ^~~~~~~~~~~
board.c:133:6: error: ‘red_LED_on’ aliased to external symbol ‘__red_LED_on’
  133 | void red_LED_on(void) __attribute__((weak, alias("__red_LED_on")));
      |      ^~~~~~~~~~
```

might be completely unrelated though.

Thanks!

**Comment by autra** [comment]
Fixed this by removing all the inlines...
